// Code generated by go generate; DO NOT EDIT.
package main

import (
	"errors"
	"fmt"

	"github.com/mitchellh/mapstructure"

	"github.com/philippgille/gokv"
	"github.com/philippgille/gokv/encoding"
	"github.com/philippgille/gokv/mongodb"
	"github.com/philippgille/gokv/redis"
)

func createStore(implementation string, codec encoding.Codec, config interface{}) (store gokv.Store, err error) {
	switch implementation {

	case "redis":
		options := redis.DefaultOptions
		options.Codec = codec
		if err := mapstructure.Decode(config, &options); err != nil {
			return nil, err
		}
		return redis.NewClient(options)
	case "mongodb":
		options := mongodb.DefaultOptions
		options.Codec = codec
		if err := mapstructure.Decode(config, &options); err != nil {
			return nil, err
		}
		return mongodb.NewClient(options)
	}

	return nil, errors.New(fmt.Sprint("unsupported implementation: ", implementation))
}
